apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<dev-aws-account-id>:role/prometheus_remote_ingest
